version: "3.8"
services:
  jaeger:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      "SPAN_STORAGE_TYPE": "grpc-plugin"
      "GRPC_STORAGE_PLUGIN_BINARY": "/go/bin/jaeger-kusto"
      "CLIENT_ID": ""
      "CLIENT_SECRET": ""
      "TENANT_ID": ""
      "ENDPOINT": ""
      "DATABASE": "jaeger"
    command: "--log-level debug"
  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - "8080-8083:8080-8083"
    restart: unless-stopped
    environment:
      "JAEGER_AGENT_HOST": "jaeger"
      "JAEGER_AGENT_PORT": "6831"