name: master

on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]

jobs:
  golangci-lint:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build & Test
    runs-on: ubuntu-latest
    needs: golangci-lint
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.6
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
              ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go mod download

      - name: Build
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v .

      - name: Build collector
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dodopizza/jaeger-kusto-collector
          dockerfile: build/plugin/Dockerfile.collector
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build query
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dodopizza/jaeger-kusto-query
          dockerfile: build/plugin/Dockerfile.query
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          
      - name: Build agent
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dodopizza/jaeger-kusto-agent
          dockerfile: build/plugin/Dockerfile.agent
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
            
      - name: Build all in one
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dodopizza/jaeger-kusto
          dockerfile: build/plugin/Dockerfile
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build plugin standalone
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dodopizza/jaeger-kusto-plugin
          dockerfile: build/server/Dockerfile
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
